_core:
  default_config_hash: UO0G2jwvL9UV3r31ivYZNVNyV5X8_C6wWjLFh4yPv3w
enabled: 1
inline: 1
plugins:
  contrast: contrast
  font_size: font_size
  letter_spacing: letter_spacing
  line_height: line_height
  images: images
  font_style: font_style
  cursor: 0
  reading_line: 0
